[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "cyclozarin"
name = "LeekPresence"
description = "A mod that expands integration of Discord Rich Presence in Content Warning"
websiteUrl = "https://github.com/cyclozarin/LeekPresence"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Hamunii-AutoHookGenPatcher = "1.0.2"

[build]
icon = "icon.png"
readme = "../../README.md"
outdir = "../dist"

[[build.copy]]
source = "../bin/Release/netstandard2.1/cyclozarin.contentwarning.LeekPresence.dll"
target = "/BepInEx/plugins/LeekPresence/"

[publish]
communities = [ "content-warning" ]
[publish.categories]
content-warning = [ "mods" ]
# For a list of valid tags, look at the slug values in https://thunderstore.io/api/experimental/community/content-warning/category/
